### ISSUE TITLE
Buttons & Icons 

### ISSUE THREAD

**Issue by ngoiyaeric** [QueueLab/MapGPT#32]
I've created space for some icons for additional functionality. At the moment, I'd like for these icons to only be clickable without any additional functionality for now.
Icons should have the ability to animate when clicked as well as adjust to theme.

![Untitled design (16)](https://github.com/QueueLab/MapGPT/assets/115367894/03ae38ac-48c8-4e89-863e-cd6a9ca750b0)

**Comment by ngoiyaeric** [comment]
https://drive.google.com/file/d/1DO-I5oUBy9284GsLv7pYyChCZjlevKZ7/view?usp=sharing
top left icon.

**Comment by ngoiyaeric** [comment]
<img width="659" alt="Screen Shot 2024-06-09 at 9 36 18 AM" src="https://github.com/QueueLab/MapGPT/assets/115367894/92b762c0-28b9-4665-8985-48510e23afdb">
one more clickable do nothing for now icon.

**Comment by ngoiyaeric** [comment]
@rosaleensiroosi Is this something you can manage next week?

**Comment by rosaleensiroosi** [comment]
yes, this is definitely something i can manage! :)

**Comment by rosaleensiroosi** [comment]
since there isn't any treehouse icon on lucide, which other icon would you prefer? i've included screenshots of the options when searching up house and tree on their icon data base. i think the icon closest to a treehouse is the tent. 
<img width="825" alt="image" src="https://github.com/QueueLab/MapGPT/assets/171291607/a780c839-c802-441d-b615-f3c3024b0995">
<img width="805" alt="image" src="https://github.com/QueueLab/MapGPT/assets/171291607/4da6f29c-6ccd-477d-a878-917b7c10f7e3">

**Comment by ngoiyaeric** [comment]
A tent works for now.

**Comment by ngoiyaeric** [comment]
Could you add a screenshot for that
